version: "3"
services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27027:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 15June199815June1998__

  db_account:
    image: postgres
    restart: always
    env_file:
      - .env.dev.account-db
    volumes:
      - postgres_data_develop:/var/lib/postgresql/data

  miousify_store_resource:
    image: miousify_store_resource:v0.0.1
    depends_on:
      - mongo


  db_tower:
    image: postgres
    restart: always
    env_file:
      - .env.dev.tower-db
    volumes:
      - postgres_data_develop2:/var/lib/postgresql/data

  miousify_account:
    image: miousify/account_service:v0.0.1
    depends_on:
      - db_account
    env_file:
      - ./.env.dev.tower
    ports:
      - 5050:80


  miousify_tower:
    image: miousify/tower_service:v0.0.1
    depends_on:
      - db_tower
    env_file:
      - ./.env.dev.account
    ports:
      - 3030:80

volumes:
  postgres_data_develop: {}
  postgres_data_develop2: {}

