version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5050:5432
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data_develop:/var/lib/postgresql/data

  miousify_account:
    image: miousify_account_service:v0.0.1

    env_file:
      - ./.env.prod.account
    ports:
      - 4000:80

volumes:
  postgres_data_develop:
