version: "3"
services:
  traefik:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker=true --providers.docker.swarmMode=true --providers.docker.network=traefik-public --entryPoints.web.address=:80
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 0s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik-dashboard.rule=Host(`xyz-dashboard.miousify.com`)"
        - "traefik.http.routers.traefik-dashboard.entrypoints=web"
        - "traefik.http.routers.traefik-dashboard.service=traefik-dashboard"
        - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"
        - "traefik.http.services.traefik-dashboard.loadbalancer.server.scheme=http"
        - "traefik.docker.lbswarm=false"

  miousify_account:
    image: miousify/account_service:latest
    networks:
      - traefik-public
    env_file:
      - ./.env.prod.account
    deploy:
      update_config:
        parallelism: 1
        delay: 0s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.miousify_account.rule=Host(`xyz-accounts.miousify.com`)"
        - "traefik.http.routers.miousify_account.entrypoints=web"
        - "traefik.http.routers.miousify_account.service=miousify_account"
        - "traefik.http.services.miousify_account.loadbalancer.server.port=80"
        - "traefik.http.services.miousify_account.loadbalancer.server.scheme=http"
        - "traefik.docker.lbswarm=false"

  whoami:
    image: containous/whoami:latest
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Path(`test.miousify.com`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.routers.whoami.service=whoami"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.services.whoami.loadbalancer.server.scheme=http"
        - "traefik.docker.lbswarm=false"

networks:
  traefik-public:
    driver: traefik-pubic
    external: true